#!/bin/sh

if [ -x /usr/local/emhttp/plugins/lucky/scripts/lucky-autostart ]; then
  /usr/local/emhttp/plugins/lucky/scripts/lucky-autostart array >/dev/null 2>&1 &
fi

if [ -x /usr/local/emhttp/plugins/lucky/scripts/lucky-update-schedule ]; then
  /usr/local/emhttp/plugins/lucky/scripts/lucky-update-schedule apply >/dev/null 2>&1 || true
fi
